// Run the shipped HTML and app with distinct daily API replies. Synthetic data only.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {JSDOM}=require('jsdom');
const dom=new JSDOM(fs.readFileSync(__dirname+'/index.html','utf8'),{url:'http://calendar.example.test/',runScripts:'outside-only'});
const context=dom.getInternalVMContext(),q=s=>dom.window.document.querySelector(s),all=s=>[...dom.window.document.querySelectorAll(s)];
const source=fs.readFileSync(__dirname+'/app.js','utf8').replace("window.addEventListener('DOMContentLoaded',()=>api('/api/session').then(acceptSession).catch(leaveWorkspace),{once:true});",'');
const dates=['2026-12-28','2026-12-29','2026-12-30','2026-12-31','2027-01-01','2027-01-02','2027-01-03'];
const utc=(day,time)=>new Date(day+'T'+time+':00+03:00').toISOString();
const snapshot=date=>({timezone:'Europe/Moscow',services:[{id:1,name:'Услуга',duration_minutes:45,active:true}],masters:[{id:1,name:'Мастер А',active:true,service_ids:[1]},{id:2,name:'Мастер Б',active:true,service_ids:[1]},{id:3,name:'Неактивный мастер',active:false,service_ids:[1]}],rooms:[{id:1,name:'Кабинет А',active:true,service_ids:[1]},{id:2,name:'Кабинет Б',active:true,service_ids:[1]}],weekly_schedule:Array.from({length:7},(_,weekday)=>[{weekday,master_id:1,start_minute:540,end_minute:1080},{weekday,room_id:1,start_minute:540,end_minute:1080}]).flat(),delivery_issues:[],bookings:dates.includes(date)?[{id:dates.indexOf(date)+1,master_id:1,room_id:1,start_utc:utc(date,'09:15'),end_utc:utc(date,'10:00'),status:'confirmed',service_name_snapshot:'Запись '+date,master_name_snapshot:'Мастер А',room_name:'Кабинет А',phone:'+79990000000'}]:[]});
const requests=[];let reply=date=>snapshot(date),checks=0;
dom.window.fetch=async(path,options)=>{
  requests.push({path,options});
  if(path.startsWith('/api/snapshot'))return {ok:true,json:async()=>reply(new URL(path,dom.window.location.href).searchParams.get('date'))};
  return {ok:true,json:async()=>path==='/api/shared-masters'?{masters:[]}:{types:[],entities:[]}};
};
vm.runInContext(source,context);const run=code=>vm.runInContext(code,context);
const check=(name,fn)=>{fn();checks++;console.log('PASS '+name);};
const edit=(selector,value)=>{q(selector).value=value;q(selector).dispatchEvent(new dom.window.Event('change',{bubbles:true}));};
const until=async fn=>{for(let i=0;i<100;i++){if(fn())return;await new Promise(r=>setTimeout(r,5));}throw Error('Calendar did not settle');};
(async()=>{
  run("salonId='1';salonRevision=1;csrf='synthetic-csrf';calendarDateExplicit=true;$('#day').value='2026-12-30';");
  await run('load()');
  check('week crossing year has seven dated Monday–Sunday columns',()=>assert.deepEqual(all('.week-day-schedule').map(el=>el.dataset.date),dates));
  check('all seven real daily API replies appear once',()=>{assert.equal(all('[data-booking]').length,7);assert.deepEqual(requests.filter(r=>r.path.startsWith('/api/snapshot')).map(r=>new URL(r.path,dom.window.location.href).searchParams.get('date')).sort(),dates);});
  check('weekly count includes all days',()=>assert.equal(q('#booking-count').textContent,'7'));
  check('quarter-hour appointment keeps precise time and salon date',()=>{assert.equal(q('[data-booking="1"]').closest('[data-date]').dataset.date,dates[0]);assert.match(q('[data-booking="1"]').textContent,/09:15–10:00/);assert(Math.abs(parseFloat(q('[data-booking="1"]').style.top)-100/36)<0.0001);});
  check('week reads preserve selected salon header',()=>assert(requests.filter(r=>r.path.startsWith('/api/snapshot')).every(r=>r.options.headers['X-Salon-Id']==='1')));
  const original=reply;
  reply=date=>{const s=original(date);if(date===dates[0])s.bookings.push(...[2,3,999].map((master_id,i)=>({...s.bookings[0],id:20+i,master_id,room_id:2,master_name_snapshot:'Мастер '+master_id,service_name_snapshot:'<img src=x onerror=bad()>',start_utc:utc(date,'09:30'),end_utc:utc(date,'10:15')})));return s;};
  await run('load()');
  check('inactive and absent resources retain appointments in All view',()=>assert.equal(all('[data-date="2026-12-28"] [data-booking]').length,4));
  check('simultaneous appointments use different horizontal positions',()=>assert.equal(new Set(all('[data-date="2026-12-28"] [data-booking]').map(el=>el.style.left)).size,4));
  check('booking names render as text, never markup',()=>{assert(!q('.week-grid img'));assert.match(q('[data-booking="20"]').textContent,/<img/);});
  edit('#calendar-resource','2');
  check('master filter retains all days and only chosen appointments',()=>{assert.equal(all('.week-day-schedule').length,7);assert.deepEqual(all('[data-booking]').map(el=>el.dataset.booking),['20']);});
  q('[data-view="rooms"]').click();
  check('room mode resets resource filter and preserves week',()=>{assert.equal(q('#calendar-resource').value,'');assert.equal(all('[data-booking]').length,10);assert.equal(q('[data-view="rooms"]').getAttribute('aria-pressed'),'true');});
  q('[data-booking="20"]').click();
  check('compact appointment opens complete inline details and scoped cancel control',()=>{assert.match(q('.week-detail').textContent,/09:30–10:15/);assert.match(q('.week-detail').textContent,/79990000000/);assert.equal(q('.week-detail [data-cancel]').dataset.cancel,'20');});
  q('[data-close-booking]').click();
  check('details close without changing appointments',()=>{assert(!q('.week-detail'));assert.equal(all('[data-booking]').length,10);});
  q('#week-next').click();await until(()=>run("calendarState==='ready'")&&all('.week-day-schedule')[0]?.dataset.date==='2027-01-04');
  check('next week shifts seven days across year',()=>assert.equal(q('#day').value,'2027-01-06'));
  q('#week-prev').click();await until(()=>run("calendarState==='ready'")&&all('.week-day-schedule')[0]?.dataset.date===dates[0]);
  check('previous week restores Sunday appointments',()=>assert(q('[data-date="2027-01-03"] [data-booking="7"]')));
  reply=date=>{if(date===dates[3])throw Error('Synthetic missing day');return original(date);};
  await assert.rejects(run('load()'),/Synthetic missing day/);
  check('failed day hides entire week with retry instruction',()=>{assert.equal(all('.week-day-schedule').length,0);assert.match(q('#calendar-week-status').textContent,/Не удалось загрузить всю неделю/);});
  reply=date=>{const s=original(date);if(date===dates[0])s.bookings.push({...s.bookings[0],id:400,start_utc:'invalid'});return s;};
  await assert.rejects(run('load()'),/некорректные данные записи/);
  check('malformed dates fail before totals or calendar state are committed',()=>{assert.equal(run('calendarWeek'),null);assert.equal(q('#booking-count').textContent,'—');assert.equal(q('#room-pressure').textContent,'—');assert.equal(all('[data-booking]').length,0);});
  reply=date=>({...original(date),bookings:[]});await run('load()');
  check('empty week still displays seven days and working hours',()=>{assert.equal(all('.week-day-schedule').length,7);assert.equal(all('[data-booking]').length,0);assert.equal(all('.week-working').length,7);assert.equal(q('#booking-count').textContent,'0');});
  reply=date=>{const s=original(date);if(date===dates[3])s.bookings.push(...[0,1,2].map(i=>({...s.bookings[0],id:500+i,start_utc:utc(date,'11:0'+i),end_utc:utc(date,'11:0'+(i+1))})));return s;};await run('load()');
  check('neighboring one-minute appointments keep separate visible tracks',()=>assert.equal(new Set([500,501,502].map(id=>q('[data-booking="'+id+'"]').style.left)).size,3));
  edit('#day','');
  check('clearing date retains the selected day and week',()=>{assert.equal(q('#day').value,'2026-12-30');assert.equal(all('.week-day-schedule').length,7);});
  run('clearSalon()');
  check('salon switch clears week, resource and booking details immediately',()=>{assert.equal(run('calendarWeek'),null);assert.equal(q('#lanes').textContent,'');assert.equal(q('#calendar-resource').value,'');});
  console.log(checks+' weekly calendar DOM/API checks passed (synthetic replies; no browser geometry or production API).');
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(()=>dom.window.close());
